#!/bin/bash
# Downloads all games specified in file passed as first argument, saves them in games directory
# Usage: ./download-all-games game-list-ids

mkdir games

while read line
do
    gameId="$line"
	wget https://online-go.com/api/v1/games/"$gameId"/sgf -O games/"$gameId".sgf
done < "$1"
