int getTransformationBit(int i, int transformations);
int getNumericalCoordinate(char c, int boardSize);
int setTransformationBit(int i, int *transformations);
int unsetTransformationBit(int i, int *transformations);
int getNumericX(char c, int boardSize);
int getNumericY(char c, int boardSize);
int getAlphabeticX(int i, int boardSize);
int getAlphabeticY(int i, int boardSize);
int getAlphabeticXY(int x, int y, int boardSize, char *letters);
int getAlphabeticXYfromIndexes(int i, int j, int boardSize, char *letters);
