#!/bin/bash

USAGE=`basename "$0"`" [SGF FILE]"
DESCRIPTION="Prints board size of the passed game."

if [[ "$#" -ne 1 || "$1" == "--help" ]]; then
	echo -e "Usage: $USAGE"; echo -e "$DESCRIPTION"; exit
fi

#########

query-game-for "$1" SZ

