#!/bin/bash

USAGE="board-size [game file]"
EXPLANATION="Prints board size of the passed game."

if [[ "$?" -eq 0 ]]; then
	echo -e "Usage: $USAGE"; echo -e "$EXPLANATION"; exit
fi

#########

game=`cat "$1"`

while read -r line; do
	result=`echo "$line" | grep '^SZ\[.*$'` 
	if [[ -n "$result" ]]; then
		echo `echo "$result" | grep '[0-9]*' -o`
		break
	fi
done <<< "$game"

