#!/bin/bash

USAGE=`basename "$0"`" [NO OF MOVES] [SGF FILE]"
DESCRIPTION="Prints first move of the passed game."

if [[ "$#" -ne 2 || "$1" == "--help" ]]; then
	echo -e "Usage: $USAGE"; echo -e "$DESCRIPTION"; exit
fi

#########

# TODO: not finished, for now just a copy of first-move 

game=`cat "$1"`

while read -r line; do
	move=`echo "$line" | grep '^;[BW]\[[a-z][a-z]\]$'`
	if [[ -n "$move" ]]; then
		echo `echo "$move" | tr -d ';BW[]'`
		break
	fi
done <<< "$game"

