#!/bin/bash

# Prints first move of the passed game

# If any arguments, use first one as games filename, else read from the pipe
game=""
if [[ "$#" -gt 0 ]]; then
    game=`cat "$1"`
else    
    game=`cat`
fi

while read -r line; do
	move=`echo "$line" | grep '^;[BW]\[[a-z][a-z]\]$'`
	if [[ -n "$move" ]]; then
		echo `echo "$move" | tr -d ';BW[]'`
		break
	fi
done <<< "$game"

