#!/bin/bash

# Prints first move of the passed game

# If any arguments, use first one as games filename, else read from the pipe
game=""
if [[ "$#" -gt 0 ]]; then
    game=`cat "$1"`
else    
    game=`cat`
fi

while read -r line; do
	result=`echo "$line" | grep '^RE\[.*$'` 
	if [[ -n "$result" ]]; then
		echo `echo "$result" | grep '[WB]' -o`
		break
	fi
done <<< "$game"

