#!/bin/bash

USAGE=`basename "$0"`" [SGF FILE]..."
DESCRIPTION="Prints number of wins and loses for every starting move among the passed games. Only analyzes 9x9 games."

if [[ "$#" -eq 0 || "$1" == "--help" ]]; then
	echo -e "Usage: $USAGE"; echo -e "$DESCRIPTION"; exit
fi

#########

noOfGames=`echo $@ | wc -w`
i=1

for game in "$@"; do 
	echo `basename "$0"`": analizing game no $i/$noOfGames: $game" >&2
	size=`board-size "$game"` 
	if [[ "$size" != '9' ]] 
		then continue 
	fi 
	winner=`winner "$game"` 
	if [[ -z "$winner" ]] 
		then continue 
	fi 
	firstMove=`first-move "$game"` 
	if [[ -z "$firstMove" ]] 
		then continue 
	fi 
	echo "$firstMove $winner" 
	let i="$i"+1
done | sort | uniq -c

