#!/bin/bash

USAGE=`basename "$0"`" game-list-ids"
DESCRIPTION="Downloads from www.online-go.com all games with id specified in file passed as first argument, saves them in games directory"

if [[ "$#" -ne 1 || "$1" == "--help" ]]; then
	echo -e "Usage: $USAGE"; echo -e "$DESCRIPTION"; exit
fi

#########

mkdir games

while read line; do
    gameId="$line"
	wget https://online-go.com/api/v1/games/"$gameId"/sgf -O games/"$gameId".sgf
done < "$1"

