#!/bin/bash

USAGE=`basename "$0"`" [game id]..."
DESCRIPTION="Downloads specified games from www.online-go.com, saves them in games directory"

if [[ "$#" -eq 0 || "$1" == "--help" ]]; then
	echo -e "Usage: $USAGE"; echo -e "$DESCRIPTION"; exit
fi

#########

mkdir games

for gamedId in "$@"; do
	wget https://online-go.com/api/v1/games/"$gameId"/sgf -O games/"$gameId".sgf
done

