#!/bin/bash

USAGE="./download-games-on-list game-list-ids"
EXPLANATION="Downloads from www.online-go.com all games with id specified in file passed as first argument, saves them in games directory"

if [[ "$#" -eq 0 ]]; then
	echo -e "Usage: $USAGE"; echo -e "$EXPLANATION"; exit
fi

#########

mkdir games

while read line; do
    gameId="$line"
	wget https://online-go.com/api/v1/games/"$gameId"/sgf -O games/"$gameId".sgf
done < "$1"

