#!/bin/bash

USAGE="./get-game-ids-from-html game-list-html"
EXPLANATION="Pass this script filename of html file with list of games and it will return this games urls, one per line."

if [[ "$#" -eq 0 ]]; then
	echo -e "Usage: $USAGE"; echo -e "$EXPLANATION"; exit
fi

#########

cat "$1" | grep /game | sed 's/class.*//g' | sed 's/[^0-9]*//g'

