#!/bin/bash

USAGE=`basename "$0"`" game-list-html"
DESCRIPTION="Pass this script filename of html file with list of games and it will return this games urls, one per line."

if [[ "$#" -ne 1 || "$1" == "--help" ]]; then
	echo -e "Usage: $USAGE"; echo -e "$DESCRIPTION"; exit
fi

#########

cat "$1" | grep /game | sed 's/class.*//g' | sed 's/[^0-9]*//g'

